USE EMPLOYEEDB;
GO

UPDATE EMPLOYEE
SET EMAIL='DILSHAD@GMAIL.COM'
WHERE EMPID=1;
UPDATE EMPLOYEE
SET EMAIL='AMAN@GMAIL.COM'
WHERE EMPID=2;
UPDATE EMPLOYEE
SET EMAIL='RIYA@GMAIL.COM'
WHERE EMPID=3;
UPDATE EMPLOYEE
SET EMAIL='RAHUL@GMAIL.COM'
WHERE EMPID=4;
